### ISSUE TITLE
Ignore segments feature proposal

### ISSUE THREAD

**Issue by michaelperrin** [mpetazzoni/leaflet-gpx#57] opened 2017-05-20 10:44 UTC
First of all, thank you for your great library :)

I have some GPX files with several segments (`<trkseg></trkseg>` tags), which results in several start and end icons being displayed on the map, and gaps in the displayed track.

Would it make sense to add an option that would only show one track, and with only one start icon (the start point of the first track segment) and one end icon on the map (the end point of the last track segment)? This option could be called like `ignoreSegments` (with the `false` value by default).

If you think this is overkill, feel free to close this issue, and I will edit my GPX files instead.
To the contrary, if you think that could be an interesting feature, I can open a PR implementing it.

**Comment by mpetazzoni** [comment] 2024-08-02 02:28
Closing as duplicate of https://github.com/mpetazzoni/leaflet-gpx/issues/123

**Closed by mpetazzoni** 2024-08-02 02:28 UTC
