### ISSUE TITLE
GPX files with multiple <trk> segments - how to dissect?

### ISSUE THREAD

**Issue by mhaberler** [mpetazzoni/leaflet-gpx#85] opened 2019-12-22 14:42 UTC
how would I load this [example GPX](https://static.mah.priv.at/public/trajectory__2019-12-28T11_00_00.gpx) and dissect into separate named tracks?

**Comment by mpetazzoni** [comment] 2019-12-28 06:04
Duplicate of #60.

**Closed by mpetazzoni** 2019-12-28 06:04 UTC
Labels: duplicate
